import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import '@/app/globals.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

import '../../public/assets/css/icon.css';
import '../../public/assets/css/plugins.css';
import '../../public/assets/fonts/unicons/unicons.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="shrink-0 grow">
          <Navbar />
          {children}
          <ToastContainer />
        </div>
        <Footer />
      </body>
    </html>
  );
}
