import type { Metadata } from "next";
import Script from "next/script";

import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import "../../public/assets/fonts/unicons/unicons.css";
import "../../public/assets/css/plugins.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grow shrink-0">
          <Navbar />
          <section className="wrapper">
            {children}
          </section>
        </div>
        <Footer />
        <Script src="assets/js/plugins.js" />
        <Script src="assets/js/theme.js" />
      </body>
    </html>
  );
}
